name: Test Schedule

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Log time
        run: echo "Schedule triggered at $(date)"
